### ISSUE TITLE
Odd behaviour while adding text in newline.

### ISSUE THREAD

**Issue by samueljd** [xelahjs/xelah#17]
Not able to add new text in the editor with the correct markers. Also need the feature to insert a particular tag (eg: \v or \p) while editing. 

https://user-images.githubusercontent.com/8311862/195943437-1573f8da-50b0-4003-89d7-70d88892e612.mp4

**Comment by joelthe1** [comment]
@samueljd does this issue also happen when you keep the `\v` tags in separate lines? According to the spec those _should_ start in new lines (though we should handle it either way).

**Comment by samueljd** [comment]
Yes, That happens even if the tags are in separate lines. Initially, The markers are actually in separate lines in the new USFM file. AFAIK when they get saved back , all the empty `\v` are saved in a single line.  If there is text after each `\v` marker they are saved in individual lines or sometimes a new line gets inserted between the text and `\v` tag. I'll test this more.
